### PR TITLE
Create Pattern36.c

### PR DESCRIPTION
**Pull request by 20a31a05e8**
## Related Issue 

Closes: #58

#### Describe the changes you've made ✍
.For the given input 7 the following pattern should print using C language

pattern36c

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@20a31a05e8 code works fine.
Changes required:
1. Rename the file to Pattern36.c

**Review by 20a31a05e8 — COMMENTED** [review]
renamed the file name to Patter36.c

**Comment by Vishal21121** [comment]
@20a31a05e8 one more this file should be inside Pattern36 folder

**Review by 20a31a05e8 — COMMENTED** [review]
changes done

**Review by Vishal21121 — APPROVED** [review]
@20a31a05e8 ready to merge

**Pull request merged**
