### PR TITLE
create Pattern1.py file

### PR DESCRIPTION
**Pull request by RaghavLimbani**
## Related Issue 

Closes: #[issue number that you are working on]

#### Describe the changes you've made ✍
A clear and concise description of what you have done to successfully close your assigned issue.

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@RaghavLimbani code works fine, but add user input in this.

**Comment by RaghavLimbani** [comment]
Okay!

**Comment by Vishal21121** [comment]
@RaghavLimbani are you working on the changes

**Comment by RaghavLimbani** [comment]
Not for now, you can assign it to someone else, cause I got some important
work

**Comment by Vishal21121** [comment]
ok, @RaghavLimbani then I am closing this pr

**Comment by RaghavLimbani** [comment]
Thanks for the opportunity. Appreciate you work

**Pull request closed without merging**
