### PR TITLE
Create Pattern37.c

### PR DESCRIPTION
**Pull request by 20a31a05e8**
## Related Issue 

Closes: #61 

#### Describe the changes you've made ✍
add a star pattern in c

image

### CODE REVIEW

**Review by 20a31a05e8 — COMMENTED** [review]
Renamed the file name to Pattern37.c

**Comment by Vishal21121** [comment]
@20a31a05e8 just shift the file to the Pattern37 folder.

**Review by 20a31a05e8 — COMMENTED** [review]
@Vishal21121 shifted the file to folder

**Review by Vishal21121 — APPROVED** [review]
@20a31a05e8 thank you for making those changes and ready to merge.

**Pull request merged**
