### PR TITLE
Added: pattern 38 JAVA

### PR DESCRIPTION
**Pull request by LAKSHIBRO**
JAVA Pattern -38 added

Closes: #69

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@LAKSHIBRO add user input in both files and remove one space with star and one space from the else part in Pattern38.java

**Comment by Vishal21121** [comment]
@LAKSHIBRO are you working on the changes?

**Comment by LAKSHIBRO** [comment]
> @LAKSHIBRO are you working on the changes?

Yes I am, i'm sorry for the delay,
I've just got into open source, so thanks for your guidance☺️
and sure I will commit the changes sooner than later

**Comment by Vishal21121** [comment]
> > @LAKSHIBRO are you working on the changes?
> 
> Yes I am, i'm sorry for the delay, I've just got into open source, so thanks for your guidance☺️ and sure I will commit the changes sooner than later

no issue just make the required changes and make the pr.

**Comment by LAKSHIBRO** [comment]
How about now,
Is there something i still need to do??

**Review by Vishal21121 — APPROVED** [review]
@LAKSHIBRO everything works fine. If you liked this repo please give it a star ⭐.

**Pull request merged**
