### PR TITLE
Pattern44.c

### PR DESCRIPTION
**Pull request by Harshal662**
## Related Issue 

Closes: #117 

#### Describe the changes you've made ✍
added 8 star pattern which take integer as input and give output accordingly

### CODE REVIEW

**Review by Vishal21121 — APPROVED** [review]
@Harshal662 code works fine. But please get assigned and then make a pr. If you liked this repo please leave a star.

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@Harshal662 rename the file to Pattern44.c instead of pattern44.c

**Comment by Vishal21121** [comment]
@Harshal662 are you working on the changes mentioned.

**Comment by Harshal662** [comment]
yes i will upload it before midnight

**Comment by Harshal662** [comment]
done

**Review by Vishal21121 — APPROVED** [review]
@Harshal662 ok to be merged. If you like this repo please give it a star.

**Pull request merged**
