### PR TITLE
Create Pattern39.c

### PR DESCRIPTION
**Pull request by parag477**
## Related Issue 

Closes: #81

#### Describe the changes you've made ✍
I have added the file "Pattern39.c" in the repository for the issue raised. In that file I wrote the code for the star pattern same as mentioned in the image provided.

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@parag477 please check the issue pattern properly and then make another pr.

**Comment by parag477** [comment]
@Vishal21121 yes I am working on it

**Comment by parag477** [comment]
I have made the pattern look same as that in the image. Hope you find it good and merge my pr.

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@parag477 there are two changes which are required:
1. In the nth row there should be n stars printed as shown in the pattern image
2. after the nth row there should be n-3 more rows .

**Review by Vishal21121 — APPROVED** [review]
@parag477 code works fine. If you liked this repo please give it a star.

**Pull request merged**
