### PR TITLE
added swastik pattern in c

### PR DESCRIPTION
**Pull request by Kruthardh11**
added solution to the pattern 36 in c

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@Kruthardh11 code works fine, just make no = 7 instead of taking user input as for values below 3 it gives different results.

**Comment by Kruthardh11** [comment]
i made the changes

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@Kruthardh11 for the no = 7 it should print 7 rows as shown in the issue image, so do the changes accordingly.

**Review by Vishal21121 — COMMENTED** [review]
@Kruthardh11 I am closing this pr as no changes have been done

**Pull request closed without merging**
