### PR TITLE
Added a new pattern 45

### PR DESCRIPTION
**Pull request by GauriTr**
## Related Issue 

Closes: #[issue number that you are working on]

#### Describe the changes you've made ✍
A clear and concise description of what you have done to successfully close your assigned issue.

### CODE REVIEW

**Comment by GauriTr** [comment]
> I have added the user input for 45 and 46 java files but the pattern 45 python file is running fine in my system. Also i will make a separate pr for images.

pattern

**Comment by GauriTr** [comment]
image
 thanks for pointing it out i have corrected it , please check it .

**Comment by Vishal21121** [comment]
@GauriTr please make the following changes:
1. Make Pattern45.java as it was before the last commit.
2. Make Pattern45.py similar to Pattern45.java before the last commit.

I allowed Pattern45 only because it was incrementing the number of columns or the number of stars by two in each iteration and the pattern you have provided in the recent commit is already there in this repo. So please make the changes mentioned above and if any help is required please comment.

**Comment by GauriTr** [comment]
So i have fixed the things you told me too, i have made changes in the python file and the java file has been set to the original before commit form.
kindly check it and provide with what can be improved if needed.
image
This is the java pattern for pattern 45
image
This is the python output for pattern 45

**Review by Vishal21121 — APPROVED** [review]
@GauriTr code works fine. If you liked this repo please give it a star. Will you make pr for the pattern images?

**Pull request merged**
