### PR TITLE
Okello sam21 patch 4

### PR DESCRIPTION
**Pull request by OkelloSam21**
## Related Issue 

Closes: #185 

#### Describe the changes you've made ✍
I have added a java code to demonstrate the below screenshot.

#### Screenshots (if any) 📸
pattern48

### CODE REVIEW

**Review by Vishal21121 — APPROVED** [review]
@OkelloSam21 code works fine.

**Comment by Vishal21121** [comment]
@OkelloSam21 if you want to add your own patterns which are not in this repo, you can do it and the procedure is mentioned [here](https://github.com/Vishal21121/Patterns-different-language/discussions/151)

**Comment by Vishal21121** [comment]
@OkelloSam21 code works fine, but put this file in the Pattern48 folder.

**Comment by OkelloSam21** [comment]
sure

**Comment by OkelloSam21** [comment]
done

**Review by Vishal21121 — APPROVED** [review]
@OkelloSam21 ready to merge.

**Pull request merged**
