### PR TITLE
Add star pattern in Java, Pattern35

### PR DESCRIPTION
**Pull request by KunalBhardwaj136**

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@KunalBhardwaj136 code works fine, just add a print statement asking the user for a value

**Comment by KunalBhardwaj136** [comment]
ok the recommended changes are up.

**Review by Vishal21121 — APPROVED** [review]
@KunalBhardwaj136 code works fine 👍

**Comment by Vishal21121** [comment]
@KunalBhardwaj136 you can star this repo if you liked it

**Pull request merged**
