### PR TITLE
 Add Alphabet pattern in Python, Pattern 42

### PR DESCRIPTION
**Pull request by OkelloSam21**
## Related Issue #108 

Closes: #[]

#### Describe the changes you've made ✍
added alphabet pattern in python, pattern 42

### CODE REVIEW

**Review by Vishal21121 — APPROVED** [review]
@OkelloSam21 code works fine.

**Comment by Vishal21121** [comment]
@OkelloSam21 just rename the file as Pattern42.py and I will merge.

**Comment by OkelloSam21** [comment]
@Vishal21121 I'm done

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 in Pattern42.js file you have not imported the prompt.

**Comment by OkelloSam21** [comment]
> @OkelloSam21 in Pattern42.js file you have not imported the prompt.

working on it

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 First thing the code should be for node js and in node js there is no window object, for taking user input you can use the readline module.

**Comment by OkelloSam21** [comment]
> @OkelloSam21 First thing the code should be for node js and in node js there is no window object, for taking user input you can use the readline module.

Ooh sorry for that.Working on it then

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 not getting the pattern shown in the issue.

**Comment by OkelloSam21** [comment]
> @OkelloSam21 not getting the pattern shown in the issue.

I missed the logic a bit let me fix it.

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 here are the corrections:
1. In the first approach you are using `console.log` which has \n by default
2. In the second approach use `rl.question` instead of `input.question`

**Comment by OkelloSam21** [comment]
> @OkelloSam21 here are the corrections:
> 
> 1. In the first approach you are using `console.log` which has \n by default
> 2. In the second approach use `rl.question` instead of `input.question`

fine

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 not getting the desired pattern and can you show the output you are getting with your code?

**Comment by OkelloSam21** [comment]
Pattern47 js - Visual Studio Code 29_05_2023 18_31_50
 here is my out put

**Comment by Vishal21121** [comment]
> Pattern47 js - Visual Studio Code 29_05_2023 18_31_50 here is my out put

I am getting this output for the second approach and not for the first approach.

**Comment by OkelloSam21** [comment]
> > Pattern47 js - Visual Studio Code 29_05_2023 18_31_50 here is my out put
> 
> I am getting this output for the second approach and not for the first approach.

let me just remove out the first approach then make a commit for the second approach

**Review by Vishal21121 — APPROVED** [review]
@OkelloSam21 code works fine.

**Pull request merged**
