### PR TITLE
Add: Pattern48.js

### PR DESCRIPTION
**Pull request by OkelloSam21**
## Related Issue 

Closes: #184 

#### Describe the changes you've made ✍
This code shows how I have solved issue #184 using JavaScript.

#### Screenshots (if any) 📸
Pattern48 js - Patterns-different-language - Visual Studio Code 23_06_2023 15_49_17

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 getting undefined in the last row

**Comment by OkelloSam21** [comment]
> @OkelloSam21 getting undefined in the last row

How can I fix this. Need some help with it if you don't mind.

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 not getting the expected output.

**Review by OkelloSam21 — COMMENTED** [review]
commented line 47 which was causing the issue of undefined in the last line of the console output.

##before:
Pattern48 js - Patterns-different-language -2

##after
Pattern48 js - Patterns-different-language - 3

**Comment by OkelloSam21** [comment]
The code is fine now

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@OkelloSam21 code is not having the **undefined** issue but it's not giving the expected output.

**Comment by OkelloSam21** [comment]
working on it

**Review by Vishal21121 — APPROVED** [review]
@OkelloSam21 code works fine.

**Pull request merged**
