### PR TITLE
Create Pattern44.py

### PR DESCRIPTION
**Pull request by HeatherWatson1**
Code that prints an Eight shape star pattern in Python

## Related Issue 

Closes: #118

#### 
Created File pattern44.py

### CODE REVIEW

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@HeatherWatson1 code is not giving the expected output. Please check the pattern mentioned in the issue.

**Comment by HeatherWatson1** [comment]
@Vishal21121  The extra line has been removed and should match expected output now, sorry about that.

**Review by Vishal21121 — CHANGES_REQUESTED** [review]
@HeatherWatson1 For n input there should be 2*n-1 rows please correct that.

**Review by Vishal21121 — APPROVED** [review]
@HeatherWatson1 code works fine. If you like this repo please give it a star.

**Pull request merged**
