### PR TITLE
Pattern49 in cpp

### PR DESCRIPTION
**Pull request by sunny0625**
## Related Issue 

Closes: #211

#### Describe the changes you've made ✍
I've solved the Pattern49 in C++ Language. I have done to successfully close my assigned issue.

#### Screenshots 📸
image
Program Output..!

### CODE REVIEW

**Comment by Vishal21121** [comment]
@sunny0625 Thanks for making this PR, but I have asked for bash not c++. So if you could do it in bash then it would be helpful.

**Comment by sunny0625** [comment]
> @sunny0625 Thanks for making this PR, but I have asked for bash not c++. So if you could do it in bash then it would be helpful.

Okay @Vishal21121,
I will try to solve this issue.

**Comment by sunny0625** [comment]
Now issue solve,
Do you want .cpp file or I will remove then make PR?

**Comment by Vishal21121** [comment]
> Now issue solve, Do you want .cpp file or I will remove then make PR?

remove the cpp file and then make pr

**Review by Vishal21121 — APPROVED** [review]
code works fine.

**Comment by Vishal21121** [comment]
@sunny0625 Thanks for contributing.

**Pull request merged**
